"""Entity registry: importing this module registers all tables on Base.metadata."""

from .civic import (
    AuditLog,
    DisputeCase,
    JurisdictionException,
    JurisdictionRule,
    WatchSubscription,
)
from .evidence import (
    CollectorType,
    EvidenceBundle,
    EvidenceClass,
    ExtractionMethod,
    ObservationCandidate,
    PublisherType,
    SourceArtifact,
    SourcePlatform,
)
from .media import MediaObject
from .observation import ObservationClaim, VerificationEvent
from .place import ExternalPlaceRef, Operator, OperatorClaim, Place, PlaceGeometry, Zone
from .reality import AnimalFacility, ObservedPresence, RealityCandidate, StaffResponseObservation
from .rule import AccessRule, RuleCondition, RuleException, Source
from .user import PetProfile, User
from .v05 import (
    AccessPath,
    Amenity,
    BoundaryPreference,
    BoundaryProfile,
    CoexistencePolicy,
    DataLicense,
    DataSourceJob,
    Entrance,
    EventPolicy,
    FreshnessPolicy,
    Organization,
    PlacePolicyBinding,
    PolicyTemplate,
    PolicyTemplateRule,
    RuleCandidate,
    SourceMonitor,
)

__all__ = [
    "AccessPath",
    "AccessRule",
    "Amenity",
    "AnimalFacility",
    "AuditLog",
    "BoundaryPreference",
    "BoundaryProfile",
    "CoexistencePolicy",
    "CollectorType",
    "DataLicense",
    "DataSourceJob",
    "DisputeCase",
    "Entrance",
    "JurisdictionException",
    "EventPolicy",
    "EvidenceBundle",
    "EvidenceClass",
    "ExternalPlaceRef",
    "ExtractionMethod",
    "FreshnessPolicy",
    "ObservationCandidate",
    "ObservedPresence",
    "Organization",
    "PlacePolicyBinding",
    "PolicyTemplate",
    "PolicyTemplateRule",
    "PublisherType",
    "RealityCandidate",
    "RuleCandidate",
    "RuleException",
    "SourceArtifact",
    "SourceMonitor",
    "SourcePlatform",
    "JurisdictionRule",
    "MediaObject",
    "ObservationClaim",
    "Operator",
    "OperatorClaim",
    "PetProfile",
    "Place",
    "PlaceGeometry",
    "RuleCondition",
    "Source",
    "StaffResponseObservation",
    "User",
    "VerificationEvent",
    "WatchSubscription",
    "Zone",
]
