"""v09_reality_layer

Revision ID: 2c7ea6ca8e30
Revises: f2a1c7d9e034
Create Date: 2026-09-21 22:02:40.627865

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '2c7ea6ca8e30'
down_revision: str | None = 'f2a1c7d9e034'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reality_candidate',
    sa.Column('candidate_type', sa.String(length=32), nullable=False),
    sa.Column('place_id', sa.String(length=36), nullable=False),
    sa.Column('zone_id', sa.String(length=36), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_bundle_id', sa.String(length=36), nullable=True),
    sa.Column('animal_scope', sa.String(length=20), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_status', sa.String(length=24), nullable=False),
    sa.Column('reality_decision', sa.String(length=24), nullable=True),
    sa.Column('reviewer', sa.String(length=64), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('freshness_state', sa.String(length=24), nullable=True),
    sa.Column('verification_status', sa.String(length=24), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('published_claim_id', sa.String(length=36), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_bundle_id'], ['evidence_bundle.id'], name=op.f('fk_reality_candidate_evidence_bundle_id_evidence_bundle'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], name=op.f('fk_reality_candidate_place_id_place'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_reality_candidate_source_id_source'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], name=op.f('fk_reality_candidate_zone_id_zone'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reality_candidate'))
    )
    op.create_index('ix_reality_candidate_place_status', 'reality_candidate', ['place_id', 'review_status'], unique=False)
    op.create_index('ix_reality_candidate_type_status', 'reality_candidate', ['candidate_type', 'review_status'], unique=False)
    op.create_table('animal_facility',
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('place_id', sa.String(length=36), nullable=False),
    sa.Column('zone_id', sa.String(length=36), nullable=True),
    sa.Column('facility_type', sa.String(length=40), nullable=False),
    sa.Column('operator_provided', sa.Boolean(), nullable=False),
    sa.Column('access_mode', sa.String(length=24), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('size_limit', sa.String(length=64), nullable=True),
    sa.Column('weather_protection', sa.Boolean(), nullable=True),
    sa.Column('shade', sa.Boolean(), nullable=True),
    sa.Column('ventilation', sa.Boolean(), nullable=True),
    sa.Column('water_available', sa.Boolean(), nullable=True),
    sa.Column('supervision_state', sa.String(length=64), nullable=True),
    sa.Column('security_or_lock_state', sa.String(length=64), nullable=True),
    sa.Column('operational_state', sa.String(length=24), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_bundle_id', sa.String(length=36), nullable=True),
    sa.Column('verification_status', sa.String(length=24), nullable=False),
    sa.Column('freshness_state', sa.String(length=24), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['reality_candidate.id'], name=op.f('fk_animal_facility_candidate_id_reality_candidate'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['evidence_bundle_id'], ['evidence_bundle.id'], name=op.f('fk_animal_facility_evidence_bundle_id_evidence_bundle'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], name=op.f('fk_animal_facility_place_id_place'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_animal_facility_source_id_source'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], name=op.f('fk_animal_facility_zone_id_zone'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_animal_facility'))
    )
    op.create_index('ix_animal_facility_place_type', 'animal_facility', ['place_id', 'facility_type'], unique=False)
    op.create_index('ix_animal_facility_state', 'animal_facility', ['operational_state'], unique=False)
    op.create_table('observed_presence',
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('place_id', sa.String(length=36), nullable=False),
    sa.Column('zone_id', sa.String(length=36), nullable=True),
    sa.Column('animal_scope', sa.String(length=20), nullable=False),
    sa.Column('animal_count_estimate', sa.Integer(), nullable=True),
    sa.Column('observed_action', sa.String(length=32), nullable=False),
    sa.Column('observed_context', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_bundle_id', sa.String(length=36), nullable=True),
    sa.Column('verification_status', sa.String(length=24), nullable=False),
    sa.Column('freshness_state', sa.String(length=24), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['reality_candidate.id'], name=op.f('fk_observed_presence_candidate_id_reality_candidate'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['evidence_bundle_id'], ['evidence_bundle.id'], name=op.f('fk_observed_presence_evidence_bundle_id_evidence_bundle'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], name=op.f('fk_observed_presence_place_id_place'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_observed_presence_source_id_source'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], name=op.f('fk_observed_presence_zone_id_zone'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observed_presence'))
    )
    op.create_index('ix_observed_presence_freshness', 'observed_presence', ['freshness_state'], unique=False)
    op.create_index('ix_observed_presence_place_time', 'observed_presence', ['place_id', 'observed_at'], unique=False)
    op.create_table('staff_response_observation',
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('place_id', sa.String(length=36), nullable=False),
    sa.Column('zone_id', sa.String(length=36), nullable=True),
    sa.Column('actor_role', sa.String(length=24), nullable=False),
    sa.Column('trigger_context', sa.Text(), nullable=True),
    sa.Column('response_action', sa.String(length=48), nullable=False),
    sa.Column('response_outcome', sa.Text(), nullable=True),
    sa.Column('policy_statement_verbatim', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_bundle_id', sa.String(length=36), nullable=True),
    sa.Column('verification_status', sa.String(length=24), nullable=False),
    sa.Column('freshness_state', sa.String(length=24), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['reality_candidate.id'], name=op.f('fk_staff_response_observation_candidate_id_reality_candidate'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['evidence_bundle_id'], ['evidence_bundle.id'], name=op.f('fk_staff_response_observation_evidence_bundle_id_evidence_bundle'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], name=op.f('fk_staff_response_observation_place_id_place'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_staff_response_observation_source_id_source'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], name=op.f('fk_staff_response_observation_zone_id_zone'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_response_observation'))
    )
    op.create_index('ix_staff_response_freshness', 'staff_response_observation', ['freshness_state'], unique=False)
    op.create_index('ix_staff_response_place_time', 'staff_response_observation', ['place_id', 'observed_at'], unique=False)

    # NOTE: autogenerate also detected place GIN/trgm and source index drift that
    # pre-existed this migration. They are deliberately LEFT OUT: this migration is
    # additive-only (v0.9 Reality Layer), and touching unrelated indices in the
    # same revision would blur the audit trail. See scripts/check_production_integrity.py
    # for the pre-existing index state.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_staff_response_place_time', table_name='staff_response_observation')
    op.drop_index('ix_staff_response_freshness', table_name='staff_response_observation')
    op.drop_table('staff_response_observation')
    op.drop_index('ix_observed_presence_place_time', table_name='observed_presence')
    op.drop_index('ix_observed_presence_freshness', table_name='observed_presence')
    op.drop_table('observed_presence')
    op.drop_index('ix_animal_facility_state', table_name='animal_facility')
    op.drop_index('ix_animal_facility_place_type', table_name='animal_facility')
    op.drop_table('animal_facility')
    op.drop_index('ix_reality_candidate_type_status', table_name='reality_candidate')
    op.drop_index('ix_reality_candidate_place_status', table_name='reality_candidate')
    op.drop_table('reality_candidate')
    # ### end Alembic commands ###
