"""track A: media_object for real upload chain

Revision ID: 2e0155d834eb
Revises: 864ffcfc7ccb
Create Date: 2026-09-12 10:57:43.369318

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2e0155d834eb"
down_revision: str | None = "864ffcfc7ccb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media_object",
        sa.Column("owner_type", sa.String(length=40), nullable=True),
        sa.Column("owner_id", sa.String(length=36), nullable=True),
        sa.Column("purpose", sa.String(length=40), nullable=False),
        sa.Column("privacy_class", sa.String(length=20), nullable=False),
        sa.Column("bucket", sa.String(length=120), nullable=False),
        sa.Column("object_key", sa.String(length=240), nullable=False),
        sa.Column("mime_type", sa.String(length=80), nullable=False),
        sa.Column("byte_size", sa.Numeric(precision=14), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("upload_status", sa.String(length=20), nullable=False),
        sa.Column("moderation_status", sa.String(length=20), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=True),
        sa.Column("ocr_text", sa.Text(), nullable=True),
        sa.Column("ocr_rule_candidates", sa.JSON(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_media_object_source_id_source"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_object")),
    )
    op.create_index("ix_media_object_expires", "media_object", ["expires_at"], unique=False)
    op.create_index(
        "ix_media_object_owner", "media_object", ["owner_type", "owner_id"], unique=False
    )
    op.create_index("uq_media_object_key", "media_object", ["object_key"], unique=True)
    # NOTE: ix_place_canonical_name_trgm is a functional index intentionally not in
    # model metadata; autogenerate "removal" is a false positive — do not drop.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_media_object_key", table_name="media_object")
    op.drop_index("ix_media_object_owner", table_name="media_object")
    op.drop_index("ix_media_object_expires", table_name="media_object")
    op.drop_table("media_object")
    # ### end Alembic commands ###
