"""source_monitor last_excerpt for change evidence

Revision ID: 4565819baf78
Revises: 5cb24fc8e838
Create Date: 2026-09-12 15:33:27.689592

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4565819baf78"
down_revision: str | None = "5cb24fc8e838"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Additive only: retain the last fetched excerpt so a detected source change
    # can be turned into a traceable EvidenceBundle (brief §6).
    # NOTE: alembic autogenerate also proposes dropping ix_place_canonical_name_trgm
    # (a hand-written GIN/trgm index it cannot introspect). It is preserved
    # deliberately — dropping it would silently degrade fuzzy place search.
    op.add_column("source_monitor", sa.Column("last_excerpt", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("source_monitor", "last_excerpt")
    # ### end Alembic commands ###
