"""v05 domain: candidates, monitors, templates, boundary, amenities, licenses

Revision ID: 4930732f4783
Revises: 2e0155d834eb
Create Date: 2026-09-12 11:28:09.920475

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4930732f4783"
down_revision: str | None = "2e0155d834eb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "freshness_policy",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("venue_scope", sa.String(length=40), nullable=True),
        sa.Column("rule_layer", sa.String(length=30), nullable=True),
        sa.Column("review_interval_days", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_freshness_policy")),
    )
    op.create_table(
        "organization",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization")),
    )
    op.create_table(
        "boundary_profile",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_boundary_profile_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_boundary_profile")),
    )
    op.create_index(
        op.f("ix_boundary_profile_user_id"), "boundary_profile", ["user_id"], unique=False
    )
    op.create_table(
        "data_license",
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("display_allowed", sa.Boolean(), nullable=False),
        sa.Column("storage_allowed", sa.Boolean(), nullable=False),
        sa.Column("redistribution_allowed", sa.Boolean(), nullable=False),
        sa.Column("commercial_use_allowed", sa.Boolean(), nullable=False),
        sa.Column("attribution_required", sa.Boolean(), nullable=False),
        sa.Column("license_name", sa.String(length=120), nullable=True),
        sa.Column("license_url", sa.String(length=500), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_data_license_source_id_source"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_license")),
    )
    op.create_table(
        "data_source_job",
        sa.Column("job_type", sa.String(length=30), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("target_scope", sa.JSON(), nullable=True),
        sa.Column("actor_user_id", sa.String(length=36), nullable=True),
        sa.Column("provider", sa.String(length=60), nullable=True),
        sa.Column("source_id", sa.String(length=36), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result_counts", sa.JSON(), nullable=True),
        sa.Column("errors", sa.JSON(), nullable=True),
        sa.Column("audit_ref", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_data_source_job_source_id_source"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_source_job")),
    )
    op.create_index("ix_job_type_state", "data_source_job", ["job_type", "state"], unique=False)
    op.create_table(
        "policy_template",
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("venue_scope", sa.String(length=40), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
            name=op.f("fk_policy_template_organization_id_organization"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_template")),
    )
    op.create_index(
        op.f("ix_policy_template_organization_id"),
        "policy_template",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "access_path",
        sa.Column("place_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("from_node", sa.String(length=160), nullable=False),
        sa.Column("to_node", sa.String(length=160), nullable=False),
        sa.Column("steps", sa.JSON(), nullable=True),
        sa.Column("geometry_wkt", sa.Text(), nullable=True),
        sa.Column("animal_scope", sa.String(length=20), nullable=True),
        sa.Column("conditions", sa.JSON(), nullable=True),
        sa.Column("time_window", sa.JSON(), nullable=True),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["place.id"],
            name=op.f("fk_access_path_place_id_place"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_access_path_source_id_source"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_path")),
    )
    op.create_table(
        "boundary_preference",
        sa.Column("profile_id", sa.String(length=36), nullable=False),
        sa.Column("attribute", sa.String(length=60), nullable=False),
        sa.Column("stance", sa.String(length=30), nullable=False),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["boundary_profile.id"],
            name=op.f("fk_boundary_preference_profile_id_boundary_profile"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_boundary_preference")),
        sa.UniqueConstraint("profile_id", "attribute", name="uq_pref_profile_attr"),
    )
    op.create_table(
        "place_policy_binding",
        sa.Column("place_id", sa.String(length=36), nullable=False),
        sa.Column("template_id", sa.String(length=36), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("overrides", sa.JSON(), nullable=True),
        sa.Column("source_id", sa.String(length=36), nullable=True),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["place.id"],
            name=op.f("fk_place_policy_binding_place_id_place"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_place_policy_binding_source_id_source"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["policy_template.id"],
            name=op.f("fk_place_policy_binding_template_id_policy_template"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_place_policy_binding")),
    )
    op.create_index(
        "ix_binding_place_active", "place_policy_binding", ["place_id", "is_active"], unique=False
    )
    op.create_table(
        "policy_template_rule",
        sa.Column("template_id", sa.String(length=36), nullable=False),
        sa.Column("animal_scope", sa.String(length=20), nullable=False),
        sa.Column("action", sa.String(length=24), nullable=False),
        sa.Column("effect", sa.String(length=16), nullable=False),
        sa.Column("conditions", sa.JSON(), nullable=True),
        sa.Column("rule_layer", sa.String(length=30), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["policy_template.id"],
            name=op.f("fk_policy_template_rule_template_id_policy_template"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_template_rule")),
    )
    op.create_index(
        op.f("ix_policy_template_rule_template_id"),
        "policy_template_rule",
        ["template_id"],
        unique=False,
    )
    op.create_table(
        "source_monitor",
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("monitor_type", sa.String(length=30), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("schedule_minutes", sa.Integer(), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("etag", sa.String(length=128), nullable=True),
        sa.Column("last_modified", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("next_check_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("place_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["place.id"],
            name=op.f("fk_source_monitor_place_id_place"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_source_monitor_source_id_source"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_monitor")),
    )
    op.create_table(
        "amenity",
        sa.Column("place_id", sa.String(length=36), nullable=False),
        sa.Column("zone_id", sa.String(length=36), nullable=True),
        sa.Column("amenity_type", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["place_id"], ["place.id"], name=op.f("fk_amenity_place_id_place"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_amenity_source_id_source"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"], ["zone.id"], name=op.f("fk_amenity_zone_id_zone"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_amenity")),
    )
    op.create_index("ix_amenity_place", "amenity", ["place_id", "amenity_type"], unique=False)
    op.create_table(
        "coexistence_policy",
        sa.Column("place_id", sa.String(length=36), nullable=False),
        sa.Column("zone_id", sa.String(length=36), nullable=True),
        sa.Column("attribute", sa.String(length=60), nullable=False),
        sa.Column("value", sa.String(length=40), nullable=False),
        sa.Column("conditions", sa.JSON(), nullable=True),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["place.id"],
            name=op.f("fk_coexistence_policy_place_id_place"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_coexistence_policy_source_id_source"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["zone.id"],
            name=op.f("fk_coexistence_policy_zone_id_zone"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coexistence_policy")),
        sa.UniqueConstraint(
            "place_id",
            "zone_id",
            "attribute",
            "source_id",
            name="uq_coexistence_place_zone_attr_source",
        ),
    )
    op.create_table(
        "entrance",
        sa.Column("place_id", sa.String(length=36), nullable=False),
        sa.Column("zone_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("entrance_type", sa.String(length=30), nullable=False),
        sa.Column("location_wkt", sa.Text(), nullable=True),
        sa.Column("access_notes", sa.String(length=400), nullable=True),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["place_id"], ["place.id"], name=op.f("fk_entrance_place_id_place"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_entrance_source_id_source"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"], ["zone.id"], name=op.f("fk_entrance_zone_id_zone"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entrance")),
    )
    op.create_table(
        "event_policy",
        sa.Column("place_id", sa.String(length=36), nullable=False),
        sa.Column("zone_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("animal_scope", sa.String(length=20), nullable=False),
        sa.Column("action", sa.String(length=24), nullable=False),
        sa.Column("effect", sa.String(length=16), nullable=False),
        sa.Column("conditions", sa.JSON(), nullable=True),
        sa.Column("time_window", sa.JSON(), nullable=True),
        sa.Column("recurrence", sa.String(length=40), nullable=True),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["place.id"],
            name=op.f("fk_event_policy_place_id_place"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_event_policy_source_id_source"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"], ["zone.id"], name=op.f("fk_event_policy_zone_id_zone"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_policy")),
    )
    op.create_index(
        "ix_event_policy_window", "event_policy", ["effective_from", "effective_to"], unique=False
    )
    op.create_table(
        "rule_candidate",
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("place_id", sa.String(length=36), nullable=True),
        sa.Column("zone_id", sa.String(length=36), nullable=True),
        sa.Column("animal_scope", sa.String(length=20), nullable=True),
        sa.Column("action", sa.String(length=24), nullable=True),
        sa.Column("effect", sa.String(length=16), nullable=True),
        sa.Column("proposed_conditions", sa.JSON(), nullable=True),
        sa.Column("extraction_method", sa.String(length=40), nullable=False),
        sa.Column("extraction_provider", sa.String(length=60), nullable=True),
        sa.Column("internal_confidence", sa.Float(), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column("review_status", sa.String(length=20), nullable=False),
        sa.Column("reviewer_id", sa.String(length=36), nullable=True),
        sa.Column("review_note", sa.String(length=500), nullable=True),
        sa.Column("published_rule_id", sa.String(length=36), nullable=True),
        sa.Column("media_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["place.id"],
            name=op.f("fk_rule_candidate_place_id_place"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_rule_candidate_source_id_source"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["zone.id"],
            name=op.f("fk_rule_candidate_zone_id_zone"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_candidate")),
    )
    op.create_index("ix_candidate_place", "rule_candidate", ["place_id"], unique=False)
    op.create_index("ix_candidate_status", "rule_candidate", ["review_status"], unique=False)
    op.add_column("access_rule", sa.Column("rule_layer", sa.String(length=30), nullable=True))
    op.add_column(
        "access_rule", sa.Column("origin_authority", sa.String(length=160), nullable=True)
    )
    op.add_column("access_rule", sa.Column("organization_id", sa.String(length=36), nullable=True))
    op.add_column(
        "access_rule", sa.Column("policy_template_id", sa.String(length=36), nullable=True)
    )
    op.add_column("access_rule", sa.Column("event_policy_id", sa.String(length=36), nullable=True))
    op.add_column(
        "access_rule", sa.Column("freshness_policy_id", sa.String(length=36), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("access_rule", "freshness_policy_id")
    op.drop_column("access_rule", "event_policy_id")
    op.drop_column("access_rule", "policy_template_id")
    op.drop_column("access_rule", "organization_id")
    op.drop_column("access_rule", "origin_authority")
    op.drop_column("access_rule", "rule_layer")
    op.drop_index("ix_candidate_status", table_name="rule_candidate")
    op.drop_index("ix_candidate_place", table_name="rule_candidate")
    op.drop_table("rule_candidate")
    op.drop_index("ix_event_policy_window", table_name="event_policy")
    op.drop_table("event_policy")
    op.drop_table("entrance")
    op.drop_table("coexistence_policy")
    op.drop_index("ix_amenity_place", table_name="amenity")
    op.drop_table("amenity")
    op.drop_table("source_monitor")
    op.drop_index(op.f("ix_policy_template_rule_template_id"), table_name="policy_template_rule")
    op.drop_table("policy_template_rule")
    op.drop_index("ix_binding_place_active", table_name="place_policy_binding")
    op.drop_table("place_policy_binding")
    op.drop_table("boundary_preference")
    op.drop_table("access_path")
    op.drop_index(op.f("ix_policy_template_organization_id"), table_name="policy_template")
    op.drop_table("policy_template")
    op.drop_index("ix_job_type_state", table_name="data_source_job")
    op.drop_table("data_source_job")
    op.drop_table("data_license")
    op.drop_index(op.f("ix_boundary_profile_user_id"), table_name="boundary_profile")
    op.drop_table("boundary_profile")
    op.drop_table("organization")
    op.drop_table("freshness_policy")
    # ### end Alembic commands ###
