"""evidence-first: source_artifact, evidence_bundle, observation_candidate

Revision ID: 5cb24fc8e838
Revises: b2a1c7d9e001
Create Date: 2026-09-12 15:25:59.850503

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5cb24fc8e838"
down_revision: str | None = "b2a1c7d9e001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_artifact",
        sa.Column("source_id", sa.String(length=36), nullable=True),
        sa.Column("source_platform", sa.String(length=40), nullable=False),
        sa.Column("collector_type", sa.String(length=60), nullable=True),
        sa.Column("artifact_type", sa.String(length=40), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("source_content_id", sa.String(length=200), nullable=True),
        sa.Column("media_id", sa.String(length=36), nullable=True),
        sa.Column("snapshot_ref", sa.String(length=400), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("publisher_type", sa.String(length=30), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("captured_excerpt", sa.Text(), nullable=True),
        sa.Column("storage_allowed", sa.Boolean(), nullable=False),
        sa.Column("display_allowed", sa.Boolean(), nullable=False),
        sa.Column("redistribution_allowed", sa.Boolean(), nullable=False),
        sa.Column("retention_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("data_source_job_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["data_source_job_id"],
            ["data_source_job.id"],
            name=op.f("fk_source_artifact_data_source_job_id_data_source_job"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_source_artifact_source_id_source"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_artifact")),
    )
    op.create_index("ix_artifact_collected", "source_artifact", ["collected_at"], unique=False)
    op.create_index("ix_artifact_hash", "source_artifact", ["content_hash"], unique=False)
    op.create_index("ix_artifact_source", "source_artifact", ["source_id"], unique=False)
    op.create_table(
        "evidence_bundle",
        sa.Column("artifact_id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=True),
        sa.Column("source_platform", sa.String(length=40), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("publisher_type", sa.String(length=30), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("quoted_fragment", sa.Text(), nullable=True),
        sa.Column("extracted_fragment", sa.Text(), nullable=True),
        sa.Column("evidence_class", sa.String(length=20), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("screenshot_ref", sa.String(length=400), nullable=True),
        sa.Column("snapshot_ref", sa.String(length=400), nullable=True),
        sa.Column("place_match_evidence", sa.JSON(), nullable=True),
        sa.Column("temporal_evidence", sa.JSON(), nullable=True),
        sa.Column("extraction_method", sa.String(length=40), nullable=True),
        sa.Column("extraction_model", sa.String(length=80), nullable=True),
        sa.Column("extraction_model_version", sa.String(length=40), nullable=True),
        sa.Column("derived_from_bundle_id", sa.String(length=36), nullable=True),
        sa.Column("reviewer_id", sa.String(length=36), nullable=True),
        sa.Column("review_log", sa.JSON(), nullable=True),
        sa.Column("license_metadata", sa.JSON(), nullable=True),
        sa.Column("privacy_notes", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["source_artifact.id"],
            name=op.f("fk_evidence_bundle_artifact_id_source_artifact"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_evidence_bundle_source_id_source"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_bundle")),
    )
    op.create_index("ix_evidence_artifact", "evidence_bundle", ["artifact_id"], unique=False)
    op.create_index("ix_evidence_captured", "evidence_bundle", ["captured_at"], unique=False)
    op.create_index("ix_evidence_class", "evidence_bundle", ["evidence_class"], unique=False)
    op.create_index("ix_evidence_source", "evidence_bundle", ["source_id"], unique=False)
    op.create_table(
        "observation_candidate",
        sa.Column("evidence_bundle_id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=True),
        sa.Column("place_id", sa.String(length=36), nullable=True),
        sa.Column("zone_id", sa.String(length=36), nullable=True),
        sa.Column("animal_scope", sa.String(length=20), nullable=True),
        sa.Column("observed_action", sa.String(length=40), nullable=True),
        sa.Column("spatial_context", sa.String(length=40), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("extraction_method", sa.String(length=40), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column("review_status", sa.String(length=20), nullable=False),
        sa.Column("reviewer_id", sa.String(length=36), nullable=True),
        sa.Column("review_note", sa.String(length=500), nullable=True),
        sa.Column("published_claim_id", sa.String(length=36), nullable=True),
        sa.Column("derivation_confidence", sa.Float(), nullable=True),
        sa.Column("duplicate_of_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["evidence_bundle_id"],
            ["evidence_bundle.id"],
            name=op.f("fk_observation_candidate_evidence_bundle_id_evidence_bundle"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["place.id"],
            name=op.f("fk_observation_candidate_place_id_place"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_observation_candidate_source_id_source"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["zone.id"],
            name=op.f("fk_observation_candidate_zone_id_zone"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_observation_candidate")),
    )
    op.create_index("ix_obs_candidate_place", "observation_candidate", ["place_id"], unique=False)
    op.create_index(
        "ix_obs_candidate_status", "observation_candidate", ["review_status"], unique=False
    )
    # NOTE: alembic autogenerate spuriously proposes dropping
    # ix_place_canonical_name_trgm (a hand-written GIN/trgm index it cannot
    # introspect). It is intentionally preserved — dropping it would silently
    # degrade fuzzy place search. Additive-only migration: nothing is removed.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_obs_candidate_status", table_name="observation_candidate")
    op.drop_index("ix_obs_candidate_place", table_name="observation_candidate")
    op.drop_table("observation_candidate")
    op.drop_index("ix_evidence_source", table_name="evidence_bundle")
    op.drop_index("ix_evidence_class", table_name="evidence_bundle")
    op.drop_index("ix_evidence_captured", table_name="evidence_bundle")
    op.drop_index("ix_evidence_artifact", table_name="evidence_bundle")
    op.drop_table("evidence_bundle")
    op.drop_index("ix_artifact_source", table_name="source_artifact")
    op.drop_index("ix_artifact_hash", table_name="source_artifact")
    op.drop_index("ix_artifact_collected", table_name="source_artifact")
    op.drop_table("source_artifact")
    # ### end Alembic commands ###
