"""initial schema: all domain entities

Revision ID: 864ffcfc7ccb
Revises:
Create Date: 2026-09-06 22:38:20.239879

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op

revision: str = "864ffcfc7ccb"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Extensions required by spatial types and Chinese-name search; idempotent.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("actor_user_id", sa.String(length=36), nullable=True),
        sa.Column("actor_role", sa.String(length=32), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=40), nullable=False),
        sa.Column("target_id", sa.String(length=64), nullable=False),
        sa.Column("before_state", sa.JSON(), nullable=True),
        sa.Column("after_state", sa.JSON(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("detail", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index("ix_audit_actor", "audit_log", ["actor_user_id"], unique=False)
    op.create_index("ix_audit_created", "audit_log", ["created_at"], unique=False)
    op.create_index("ix_audit_target", "audit_log", ["target_type", "target_id"], unique=False)
    op.create_table(
        "operator",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("org_type", sa.String(length=32), nullable=False),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("contact_phone", sa.String(length=32), nullable=True),
        sa.Column("website", sa.String(length=512), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("verification_method", sa.String(length=64), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operator")),
    )
    op.create_table(
        "source",
        sa.Column("source_type", sa.String(length=40), nullable=False),
        sa.Column("issuer", sa.String(length=200), nullable=False),
        sa.Column("issuer_verification", sa.String(length=20), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("source_snapshot_ref", sa.String(length=512), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_availability", sa.String(length=24), nullable=False),
        sa.Column("directness", sa.String(length=16), nullable=False),
        sa.Column("spatial_precision", sa.String(length=16), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source")),
    )
    op.create_index(op.f("ix_source_source_type"), "source", ["source_type"], unique=False)
    op.create_table(
        "user",
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("email", name=op.f("uq_user_email")),
        sa.UniqueConstraint("phone", name=op.f("uq_user_phone")),
    )
    op.create_table(
        "dispute_case",
        sa.Column("target_type", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=False),
        sa.Column("claimant_user_id", sa.String(length=36), nullable=True),
        sa.Column("reason_code", sa.String(length=64), nullable=False),
        sa.Column("notice_text", sa.Text(), nullable=False),
        sa.Column("evidence_refs", sa.JSON(), nullable=True),
        sa.Column("temporary_action", sa.String(length=24), nullable=False),
        sa.Column("counter_statement", sa.Text(), nullable=True),
        sa.Column("counter_party_user_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("resolution", sa.String(length=40), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("forwarded_to", sa.String(length=200), nullable=True),
        sa.Column("reviewer_id", sa.String(length=36), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["claimant_user_id"],
            ["user.id"],
            name=op.f("fk_dispute_case_claimant_user_id_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["counter_party_user_id"],
            ["user.id"],
            name=op.f("fk_dispute_case_counter_party_user_id_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dispute_case")),
    )
    op.create_index("ix_dispute_status", "dispute_case", ["status"], unique=False)
    op.create_index("ix_dispute_target", "dispute_case", ["target_type", "target_id"], unique=False)
    op.create_table(
        "jurisdiction_rule",
        sa.Column("jurisdiction_level", sa.String(length=16), nullable=False),
        sa.Column("jurisdiction_id", sa.String(length=64), nullable=False),
        sa.Column("authority", sa.String(length=200), nullable=False),
        sa.Column("instrument_type", sa.String(length=64), nullable=False),
        sa.Column("document_name", sa.String(length=300), nullable=False),
        sa.Column("clause_ref", sa.String(length=64), nullable=True),
        sa.Column("clause_text_ref", sa.String(length=512), nullable=True),
        sa.Column("animal_scope", sa.String(length=20), nullable=False),
        sa.Column("venue_scope", sa.String(length=64), nullable=True),
        sa.Column("action", sa.String(length=24), nullable=True),
        sa.Column("effect", sa.String(length=16), nullable=True),
        sa.Column("conditions", sa.JSON(), nullable=True),
        sa.Column("mandatory_level", sa.String(length=20), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("supersedes_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("review_status", sa.String(length=40), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_jurisdiction_rule_source_id_source"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jurisdiction_rule")),
    )
    op.create_index(
        "ix_jurisdiction_geo",
        "jurisdiction_rule",
        ["jurisdiction_level", "jurisdiction_id"],
        unique=False,
    )
    op.create_index("ix_jurisdiction_review", "jurisdiction_rule", ["review_status"], unique=False)
    op.create_table(
        "pet_profile",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column("species", sa.String(length=32), nullable=False),
        sa.Column("breed_text", sa.String(length=120), nullable=True),
        sa.Column("breed_id", sa.String(length=64), nullable=True),
        sa.Column("weight_kg", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("shoulder_height_cm", sa.Numeric(precision=6, scale=1), nullable=True),
        sa.Column("service_role", sa.String(length=32), nullable=False),
        sa.Column("registration_status", sa.String(length=32), nullable=True),
        sa.Column("vaccination_status", sa.String(length=32), nullable=True),
        sa.Column("avatar_url", sa.String(length=512), nullable=True),
        sa.Column("birth_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_pet_profile_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pet_profile")),
    )
    op.create_index(op.f("ix_pet_profile_user_id"), "pet_profile", ["user_id"], unique=False)
    op.create_table(
        "place",
        sa.Column("canonical_name", sa.String(length=200), nullable=False),
        sa.Column("place_type", sa.String(length=32), nullable=False),
        sa.Column("parent_place_id", sa.String(length=36), nullable=True),
        sa.Column("operator_id", sa.String(length=36), nullable=True),
        sa.Column("lifecycle_status", sa.String(length=32), nullable=False),
        sa.Column("canonical_address", sa.Text(), nullable=True),
        sa.Column(
            "location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("parent_place_id != id", name=op.f("ck_place_parent_not_self")),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["operator.id"],
            name=op.f("fk_place_operator_id_operator"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["parent_place_id"],
            ["place.id"],
            name=op.f("fk_place_parent_place_id_place"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_place")),
    )
    op.create_index(op.f("ix_place_lifecycle_status"), "place", ["lifecycle_status"], unique=False)
    op.create_index(
        "ix_place_location_gist", "place", ["location"], unique=False, postgresql_using="gist"
    )
    op.create_index(op.f("ix_place_place_type"), "place", ["place_type"], unique=False)
    # CJK-friendly fuzzy name search (pg_trgm); functional index, not in model metadata
    op.create_index(
        "ix_place_canonical_name_trgm",
        "place",
        ["canonical_name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"canonical_name": "gin_trgm_ops"},
    )
    op.create_table(
        "watch_subscription",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("target_type", sa.String(length=16), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=False),
        sa.Column("channels", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("last_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "target_id IS NOT NULL", name=op.f("ck_watch_subscription_needs_target")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_watch_subscription_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watch_subscription")),
        sa.UniqueConstraint("user_id", "target_type", "target_id", name="uq_watch_user_target"),
    )
    op.create_index(
        "ix_watch_target", "watch_subscription", ["target_type", "target_id"], unique=False
    )
    op.create_table(
        "external_place_ref",
        sa.Column("place_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("persistence_permission", sa.String(length=16), nullable=False),
        sa.Column("last_resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata_hash", sa.String(length=64), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["place.id"],
            name=op.f("fk_external_place_ref_place_id_place"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_place_ref")),
    )
    op.create_index(
        op.f("ix_external_place_ref_place_id"), "external_place_ref", ["place_id"], unique=False
    )
    op.create_index(
        "uq_external_ref_provider_ext",
        "external_place_ref",
        ["provider", "external_id"],
        unique=True,
    )
    op.create_table(
        "operator_claim",
        sa.Column("place_id", sa.String(length=36), nullable=False),
        sa.Column("operator_id", sa.String(length=36), nullable=False),
        sa.Column("claimant_user_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("verification_method", sa.String(length=64), nullable=True),
        sa.Column("evidence_refs", sa.JSON(), nullable=True),
        sa.Column("reviewed_by", sa.String(length=36), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["claimant_user_id"],
            ["user.id"],
            name=op.f("fk_operator_claim_claimant_user_id_user"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["operator.id"],
            name=op.f("fk_operator_claim_operator_id_operator"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["place.id"],
            name=op.f("fk_operator_claim_place_id_place"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operator_claim")),
    )
    op.create_index(
        "ix_operator_claim_place_status", "operator_claim", ["place_id", "status"], unique=False
    )
    op.create_index(op.f("ix_operator_claim_status"), "operator_claim", ["status"], unique=False)
    op.create_table(
        "zone",
        sa.Column("place_id", sa.String(length=36), nullable=False),
        sa.Column("parent_zone_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("zone_type", sa.String(length=32), nullable=False),
        sa.Column("floor_ref", sa.String(length=32), nullable=True),
        sa.Column("indoor_outdoor", sa.String(length=16), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_zone_id"],
            ["zone.id"],
            name=op.f("fk_zone_parent_zone_id_zone"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["place_id"], ["place.id"], name=op.f("fk_zone_place_id_place"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_zone")),
    )
    op.create_index(op.f("ix_zone_place_id"), "zone", ["place_id"], unique=False)
    op.create_index(op.f("ix_zone_zone_type"), "zone", ["zone_type"], unique=False)
    op.create_table(
        "access_rule",
        sa.Column("place_id", sa.String(length=36), nullable=True),
        sa.Column("zone_id", sa.String(length=36), nullable=True),
        sa.Column("animal_scope", sa.String(length=20), nullable=False),
        sa.Column("action", sa.String(length=24), nullable=False),
        sa.Column("effect", sa.String(length=16), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("rule_origin", sa.String(length=40), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("supersedes_rule_id", sa.String(length=36), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(place_id IS NOT NULL) OR (zone_id IS NOT NULL)",
            name=op.f("ck_access_rule_needs_owner"),
        ),
        sa.CheckConstraint(
            "supersedes_rule_id != id", name=op.f("ck_access_rule_supersedes_not_self")
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["place.id"],
            name=op.f("fk_access_rule_place_id_place"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_access_rule_source_id_source"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_rule_id"],
            ["access_rule.id"],
            name=op.f("fk_access_rule_supersedes_rule_id_access_rule"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"], ["zone.id"], name=op.f("fk_access_rule_zone_id_zone"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_rule")),
    )
    op.create_index(op.f("ix_access_rule_place_id"), "access_rule", ["place_id"], unique=False)
    op.create_index(
        "ix_access_rule_place_status", "access_rule", ["place_id", "status"], unique=False
    )
    op.create_index("ix_access_rule_review_due", "access_rule", ["review_due_at"], unique=False)
    op.create_index(
        "ix_access_rule_scope_action", "access_rule", ["animal_scope", "action"], unique=False
    )
    op.create_index(op.f("ix_access_rule_zone_id"), "access_rule", ["zone_id"], unique=False)
    op.create_index(
        "ix_access_rule_zone_status", "access_rule", ["zone_id", "status"], unique=False
    )
    op.create_table(
        "observation_claim",
        sa.Column("place_id", sa.String(length=36), nullable=False),
        sa.Column("zone_id", sa.String(length=36), nullable=True),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("occurred_precision", sa.String(length=16), nullable=False),
        sa.Column("reported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("animal_scope", sa.String(length=20), nullable=False),
        sa.Column("observed_action", sa.String(length=24), nullable=False),
        sa.Column("staff_action", sa.String(length=32), nullable=False),
        sa.Column("place_confidence", sa.String(length=24), nullable=False),
        sa.Column("evidence_support", sa.JSON(), nullable=True),
        sa.Column("dispute_status", sa.String(length=20), nullable=False),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("proximity_verified", sa.Boolean(), nullable=False),
        sa.Column("distance_bucket", sa.String(length=16), nullable=True),
        sa.Column("accuracy_bucket", sa.String(length=16), nullable=True),
        sa.Column("proximity_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["place.id"],
            name=op.f("fk_observation_claim_place_id_place"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_observation_claim_user_id_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["zone.id"],
            name=op.f("fk_observation_claim_zone_id_zone"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_observation_claim")),
    )
    op.create_index(
        op.f("ix_observation_claim_place_id"), "observation_claim", ["place_id"], unique=False
    )
    op.create_index(
        op.f("ix_observation_claim_user_id"), "observation_claim", ["user_id"], unique=False
    )
    op.create_index("ix_observation_dispute", "observation_claim", ["dispute_status"], unique=False)
    op.create_index(
        "ix_observation_place_reported",
        "observation_claim",
        ["place_id", "reported_at"],
        unique=False,
    )
    op.create_table(
        "place_geometry",
        sa.Column("place_id", sa.String(length=36), nullable=True),
        sa.Column("zone_id", sa.String(length=36), nullable=True),
        sa.Column("geometry_type", sa.String(length=16), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("precision", sa.String(length=16), nullable=False),
        sa.Column("coordinate_system_internal", sa.String(length=16), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(place_id IS NOT NULL) OR (zone_id IS NOT NULL)",
            name=op.f("ck_place_geometry_needs_owner"),
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["place.id"],
            name=op.f("fk_place_geometry_place_id_place"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_place_geometry_source_id_source"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["zone.id"],
            name=op.f("fk_place_geometry_zone_id_zone"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_place_geometry")),
    )
    op.create_index(
        "ix_place_geometry_geom_gist",
        "place_geometry",
        ["geom"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        op.f("ix_place_geometry_place_id"), "place_geometry", ["place_id"], unique=False
    )
    op.create_index(op.f("ix_place_geometry_zone_id"), "place_geometry", ["zone_id"], unique=False)
    op.create_table(
        "rule_condition",
        sa.Column("rule_id", sa.String(length=36), nullable=False),
        sa.Column("condition_type", sa.String(length=40), nullable=False),
        sa.Column("value_flag", sa.Boolean(), nullable=True),
        sa.Column("value_numeric", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("value_text", sa.String(length=200), nullable=True),
        sa.Column("value_json", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["access_rule.id"],
            name=op.f("fk_rule_condition_rule_id_access_rule"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_condition")),
    )
    op.create_index("ix_rule_condition_rule", "rule_condition", ["rule_id"], unique=False)
    op.create_table(
        "verification_event",
        sa.Column("place_id", sa.String(length=36), nullable=False),
        sa.Column("zone_id", sa.String(length=36), nullable=True),
        sa.Column("rule_id", sa.String(length=36), nullable=True),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("result", sa.String(length=20), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("evidence_refs", sa.JSON(), nullable=True),
        sa.Column("proximity_verified", sa.Boolean(), nullable=False),
        sa.Column("distance_bucket", sa.String(length=16), nullable=True),
        sa.Column("accuracy_bucket", sa.String(length=16), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["place.id"],
            name=op.f("fk_verification_event_place_id_place"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["access_rule.id"],
            name=op.f("fk_verification_event_rule_id_access_rule"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_verification_event_user_id_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["zone.id"],
            name=op.f("fk_verification_event_zone_id_zone"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_event")),
    )
    op.create_index(
        "ix_verification_place_created",
        "verification_event",
        ["place_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_verification_place_created", table_name="verification_event")
    op.drop_table("verification_event")
    op.drop_index("ix_rule_condition_rule", table_name="rule_condition")
    op.drop_table("rule_condition")
    op.drop_index(op.f("ix_place_geometry_zone_id"), table_name="place_geometry")
    op.drop_index(op.f("ix_place_geometry_place_id"), table_name="place_geometry")
    op.drop_index(
        "ix_place_geometry_geom_gist", table_name="place_geometry", postgresql_using="gist"
    )
    op.drop_table("place_geometry")
    op.drop_index("ix_observation_place_reported", table_name="observation_claim")
    op.drop_index("ix_observation_dispute", table_name="observation_claim")
    op.drop_index(op.f("ix_observation_claim_user_id"), table_name="observation_claim")
    op.drop_index(op.f("ix_observation_claim_place_id"), table_name="observation_claim")
    op.drop_table("observation_claim")
    op.drop_index("ix_access_rule_zone_status", table_name="access_rule")
    op.drop_index(op.f("ix_access_rule_zone_id"), table_name="access_rule")
    op.drop_index("ix_access_rule_scope_action", table_name="access_rule")
    op.drop_index("ix_access_rule_review_due", table_name="access_rule")
    op.drop_index("ix_access_rule_place_status", table_name="access_rule")
    op.drop_index(op.f("ix_access_rule_place_id"), table_name="access_rule")
    op.drop_table("access_rule")
    op.drop_index(op.f("ix_zone_zone_type"), table_name="zone")
    op.drop_index(op.f("ix_zone_place_id"), table_name="zone")
    op.drop_table("zone")
    op.drop_index(op.f("ix_operator_claim_status"), table_name="operator_claim")
    op.drop_index("ix_operator_claim_place_status", table_name="operator_claim")
    op.drop_table("operator_claim")
    op.drop_index("uq_external_ref_provider_ext", table_name="external_place_ref")
    op.drop_index(op.f("ix_external_place_ref_place_id"), table_name="external_place_ref")
    op.drop_table("external_place_ref")
    op.drop_index("ix_watch_target", table_name="watch_subscription")
    op.drop_table("watch_subscription")
    op.drop_index(op.f("ix_place_place_type"), table_name="place")
    op.drop_index("ix_place_canonical_name_trgm", table_name="place")
    op.drop_index("ix_place_location_gist", table_name="place", postgresql_using="gist")
    op.drop_index(op.f("ix_place_lifecycle_status"), table_name="place")
    op.drop_table("place")
    op.drop_index(op.f("ix_pet_profile_user_id"), table_name="pet_profile")
    op.drop_table("pet_profile")
    op.drop_index("ix_jurisdiction_review", table_name="jurisdiction_rule")
    op.drop_index("ix_jurisdiction_geo", table_name="jurisdiction_rule")
    op.drop_table("jurisdiction_rule")
    op.drop_index("ix_dispute_target", table_name="dispute_case")
    op.drop_index("ix_dispute_status", table_name="dispute_case")
    op.drop_table("dispute_case")
    op.drop_table("user")
    op.drop_index(op.f("ix_source_source_type"), table_name="source")
    op.drop_table("source")
    op.drop_table("operator")
    op.drop_index("ix_audit_target", table_name="audit_log")
    op.drop_index("ix_audit_created", table_name="audit_log")
    op.drop_index("ix_audit_actor", table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
